### ISSUE TITLE
installation with brew

### ISSUE THREAD

**Issue by mesqueeb** [egoist/dum#11]
Would be great if I could `brew install dum` ! : )

**Comment by egoist** [comment]
PR welcome, I have never submitted a package to Homebrew before.

**Comment by mesqueeb** [comment]
Me neither 😮

**Comment by lianghx-319** [comment]
I am working on this, PR for homebrew/core will be created tonight.

**Comment by lianghx-319** [comment]
How can I add a test case to make sure dum install succesed

**Comment by egoist** [comment]
Available now `brew install egoist/tap/dum`
